import * as z from "zod";

/**
 * Represents a Facebook user or page participating in the conversation.
 */
const FacebookUserSchema = z.object({
  id: z
    .string()
    .describe(
      "Unique Facebook ID of the user or page. This is a long numeric string assigned by Facebook, e.g. '25253244094345190'."
    ),
});

/**
 * Represents a message sent by the user to the Facebook Page.
 */
const FacebookMessageSchema = z.object({
  mid: z
    .string()
    .optional()
    .describe(
      "Unique message ID generated by Facebook for this message event. Used for tracking and deduplication."
    ),

  text: z
    .string()
    .optional()
    .describe(
      "Plain text message written by the user to the Facebook Page. This is natural human language such as greetings, questions, or requests. Example: 'Hello', 'I want to book a room', 'What are your opening hours?'"
    ),
});

/**
 * Represents a single messaging event (message, delivery, read, etc).
 */
const FacebookMessagingEventSchema = z.object({
  sender: FacebookUserSchema.optional().describe(
    "The user who sent the message to the Facebook Page."
  ),

  recipient: FacebookUserSchema.optional().describe(
    "The Facebook Page that received the message."
  ),

  timestamp: z
    .number()
    .optional()
    .describe(
      "Unix timestamp (in milliseconds) indicating when the event occurred. Example: 1700000000000"
    ),

  message: FacebookMessageSchema.optional().describe(
    "Message payload sent by the user. Present only when the event type is a user message."
  ),
});

/**
 * Represents a batch of messaging events delivered together.
 */
const FacebookEntrySchema = z.object({
  id: z
    .string()
    .describe(
      "Facebook Page ID that received the webhook event. Example: '1122334455667788'"
    ),

  time: z
    .number()
    .describe(
      "Unix timestamp (in milliseconds) when Facebook generated this entry. Example: 1700000000000"
    ),

  messaging: z
    .array(FacebookMessagingEventSchema)
    .optional()
    .describe(
      "List of messaging events such as messages, deliveries, or read receipts."
    ),
});

/**
 * Root webhook payload sent by Facebook to the server.
 */
export const FacebookWebhookSchema = z.object({
  object: z
    .literal("page")
    .describe(
      "Indicates the type of Facebook subscription. For Messenger webhooks, this value is always 'page'."
    ),

  entry: z
    .array(FacebookEntrySchema)
    .describe(
      "Array of webhook entries. Each entry may contain one or more messaging events."
    ),
});

export type FacebookMessagePayload = z.infer<typeof FacebookWebhookSchema>;

export const SendFacebookMessagePayload = z.object({
  recipientId: z.string().min(1, "Recipient ID is required"),
  message: z.string().min(1, "Message cannot be empty"),
});

export type SendFacebookMessagePayload = z.infer<
  typeof SendFacebookMessagePayload
>;

export const FacebookAccessTokenSchema = z
  .string()
  .min(5, "Valid facebook access token is required")
  .regex(/^[A-Za-z0-9-_]+$/, "Invalid Facebook access token format");
